# Generated by Django 4.2.6 on 2024-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
