# Generated by Django 4.2.6 on 2024-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='household',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
